// SPDX-FileCopyrightText: Nextcloud GmbH
// SPDX-FileCopyrightText: 2024 Marino Faggiana
// SPDX-License-Identifier: GPL-3.0-or-later

import UIKit

protocol NCTrashGridCellDelegate: AnyObject {
    func tapMoreGridItem(with objectId: String, image: UIImage?, sender: Any)
}

class NCTrashGridCell: UICollectionViewCell, NCTrashCellProtocol {
    @IBOutlet weak var imageItem: UIImageView!
    @IBOutlet weak var imageSelect: UIImageView!
    @IBOutlet weak var imageStatus: UIImageView!
    @IBOutlet weak var imageFavorite: UIImageView!
    @IBOutlet weak var imageLocal: UIImageView!
    @IBOutlet weak var labelTitle: UILabel!
    @IBOutlet weak var labelExtension: UILabel!
    @IBOutlet weak var labelInfo: UILabel!
    @IBOutlet weak var buttonMore: UIButton!
    @IBOutlet weak var imageVisualEffect: UIVisualEffectView!
    @IBOutlet weak var progressView: UIProgressView!

    weak var delegate: NCTrashGridCellDelegate?
    var objectId = ""

    var statusImg: UIImageView? {
        get { return nil }
        set { imageItem = newValue }
    }
    var indexPath = IndexPath()
    var account = ""
    var user = ""

    var namedButtonMore = ""

    var fileObjectId: String? {
        get { return objectId }
        set { objectId = newValue ?? "" }
    }
    var filePreviewImageView: UIImageView? {
        get { return imageItem }
        set { imageItem = newValue }
    }
    var fileUser: String? {
        get { return user }
        set { user = newValue ?? "" }
    }
    var fileTitleLabel: UILabel? {
        get { return labelTitle }
        set { labelTitle = newValue }
    }
    var fileInfoLabel: UILabel? {
        get { return labelInfo }
        set { labelInfo = newValue }
    }
    var fileProgressView: UIProgressView? {
        get { return progressView }
        set { progressView = newValue }
    }
    var fileSelectImage: UIImageView? {
        get { return imageSelect }
        set { imageSelect = newValue }
    }
    var fileStatusImage: UIImageView? {
        get { return imageStatus }
        set { imageStatus = newValue }
    }
    var fileLocalImage: UIImageView? {
        get { return imageLocal }
        set { imageLocal = newValue }
    }
    var fileFavoriteImage: UIImageView? {
        get { return imageFavorite }
        set { imageFavorite = newValue }
    }

    override func awakeFromNib() {
        super.awakeFromNib()
        initCell()
    }

    override func prepareForReuse() {
        super.prepareForReuse()
        initCell()
    }

    func initCell() {
        accessibilityHint = nil
        accessibilityLabel = nil
        accessibilityValue = nil
        isAccessibilityElement = true

        imageItem.layer.cornerRadius = 6
        imageItem.layer.masksToBounds = true

        imageVisualEffect.isHidden = false
        imageVisualEffect.effect = nil
        imageVisualEffect.alpha = 0
        imageVisualEffect.isUserInteractionEnabled = false
        imageVisualEffect.backgroundColor = UIColor.white.withAlphaComponent(0.2)

        // Dynamic Type Font Configuration
        //
        // These labels use fonts generated by the custom UIFont helpers defined in
        // the UIFont extension (e.g. `.callout()`, `.caption1()`).
        //
        // Those helpers wrap `UIFontMetrics` to provide Dynamic Type scaling while
        // applying an upper bound to the maximum font size. This ensures:
        //
        // - The text respects the user's preferred accessibility size.
        // - The UI layout remains stable and does not grow indefinitely.
        //
        // `adjustsFontForContentSizeCategory` is enabled to allow UIKit to
        // automatically update the font when the user changes the Dynamic Type
        // setting while the application is running.
        //
        // Without this flag, the label would keep the initially computed font size
        // and would not react to content size category changes.
        //
        // In summary:
        //
        // UIFont helper:
        //     Defines how the font scales and its maximum size.
        //
        // adjustsFontForContentSizeCategory:
        //     Enables live updates when accessibility settings change.
        //
//        progressView.tintColor = NCBrandColor.shared.brandElement
//        progressView.transform = CGAffineTransform(scaleX: 1.0, y: 0.5)
//        progressView.trackTintColor = .clear

        labelTitle.text = ""
        labelTitle.font = .callout()
        labelTitle.adjustsFontForContentSizeCategory = true

        labelExtension.text = ""
        labelExtension.isHidden = true
        labelExtension.font = .callout()
        labelExtension.adjustsFontForContentSizeCategory = true

        labelInfo.text = ""
        labelInfo.font = .footnote()
        labelInfo.adjustsFontForContentSizeCategory = true

//        labelSubinfo.text = ""
//        labelSubinfo.font = .footnote()
//        labelSubinfo.adjustsFontForContentSizeCategory = true

        if labelExtension.isHidden {
            labelTitle.numberOfLines = 2
            labelTitle.lineBreakMode = .byWordWrapping
        } else {
            labelTitle.numberOfLines = 1
            labelTitle.lineBreakMode = .byTruncatingTail
        }
        labelTitle.textColor = .label
        labelInfo.textColor = .systemGray
        labelSubinfo.text = ""
    }

    override func snapshotView(afterScreenUpdates afterUpdates: Bool) -> UIView? {
        return nil
    }

    @IBAction func touchUpInsideMore(_ sender: Any) {
        delegate?.tapMoreGridItem(with: objectId, image: imageItem.image, sender: sender)
    }


    fileprivate func setA11yActions() {
        let moreName = namedButtonMore == NCGlobal.shared.buttonMoreStop ? "_cancel_" : "_more_"
        
        self.accessibilityCustomActions = [
            UIAccessibilityCustomAction(
                name: NSLocalizedString(moreName, comment: ""),
                target: self,
                selector: #selector(touchUpInsideMore(_:)))
        ]
    }

    func setButtonMore(named: String, image: UIImage) {
        namedButtonMore = named
        buttonMore.setImage(image, for: .normal)
        setA11yActions()
    }

    func selected(_ status: Bool, isEditMode: Bool, color: UIColor) {
        if isEditMode {
            imageSelect.isHidden = false
            buttonMore.isHidden = true
            accessibilityCustomActions = nil
        } else {
            imageSelect.isHidden = true
            buttonMore.isHidden = false
            imageVisualEffect.isHidden = true
            setA11yActions()
        }

//        imageVisualEffect.alpha = status ? 1 : 0
//        imageSelect.alpha = status ? 1 : 0
//        imageSelect.image = NCImageCache.shared.getImageCheckedYes(color: color)
        if status {
            imageSelect.image = NCImageCache.shared.getImageCheckedYes(color: color)
            imageSelect.isHidden = false
            imageVisualEffect.isHidden = false
        } else {
            imageSelect.isHidden = true
            imageVisualEffect.isHidden = true
        }
    }

    func writeInfoDateSize(date: NSDate, size: Int64) {
        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .short
        dateFormatter.timeStyle = .none
        dateFormatter.locale = Locale.current

        labelInfo.text = dateFormatter.string(from: date as Date) + " · " + NCUtilityFileSystem().transformedSize(size)
    }

    func setAccessibility(label: String, value: String) {
        accessibilityLabel = label
        accessibilityValue = value
    }
}
