###
# SPDX-License-Identifier: AGPL-3.0
#
# Author: Bernd rederlechner <bernd.rederlechner@t-systems.com>
#
# Builds a stable release package based on a release assembly
# customisation-<version>-<increment>
#
# As soon as a package is deployed to production, the tag and the branch
# MUST STAY FOR 2 years and not deleted.
#
# Release packages, tags and customisation branches not delivered to production should
# be deleted asap a newer release is available.
#

name: MCLOUD custom client merge

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: Custom build from base branch
        options: 
          - master
          - stable-4.9.7
          - stable-5.2.1
          - stable-5.2.7
          - stable-5.5.0
          # - v3.0.8
        default: master

jobs:
  assemble-custom:
    uses: nextmcloud/.github/.github/workflows/nmc-custom-client.yml@master
    with:
      trunk: 'master'
      stable: ${{ inputs.branch }}
      result: ${{ format('customisation-{0}-{1}', github.actor, inputs.branch) }}
    secrets: inherit
